import { statusData } from "@/types/analytics"

export const demoRequestsData: statusData[] = [
  {
    name: "Organizational and Corporate Documents",
    total: 32,
    completed: 20,
    incomplete: 10,
    assigned: 2,
  },
  {
    name: "Financial and Accounting Records",
    total: 64,
    completed: 40,
    incomplete: 20,
    assigned: 4,
  },
  {
    name: "Tax Matters",
    total: 50,
    completed: 30,
    incomplete: 15,
    assigned: 5,
  },
  {
    name: "Loans and Obligations",
    total: 40,
    completed: 25,
    incomplete: 10,
    assigned: 5,
  },
  {
    name: "Property and Equipment",
    total: 30,
    completed: 18,
    incomplete: 10,
    assigned: 5,
  },
  {
    name: "Intellectual Property",
    total: 45,
    completed: 28,
    incomplete: 12,
    assigned: 5,
  },
  {
    name: "Material Contracts",
    total: 55,
    completed: 35,
    incomplete: 15,
    assigned: 5,
  },
  {
    name: "Operational Matters",
    total: 60,
    completed: 38,
    incomplete: 17,
    assigned: 5,
  },
  {
    name: "Litigation",
    total: 70,
    completed: 45,
    incomplete: 20,
    assigned: 5,
  },
  {
    name: "Regulatory Matters",
    total: 65,
    completed: 40,
    incomplete: 20,
    assigned: 5,
  },
  {
    name: "Environmental Matters",
    total: 35,
    completed: 22,
    incomplete: 8,
    assigned: 5,
  },
  {
    name: "Employment and Compensation Matters",
    total: 80,
    completed: 50,
    incomplete: 25,
    assigned: 5,
  },
  {
    name: "Data Privacy and Security",
    total: 75,
    completed: 48,
    incomplete: 22,
    assigned: 5,
  },
]

export const demoDocumentsData: statusData[] = [
  {
    name: "Organizational and Corporate Documents",
    total: 320,
    completed: 200,
    incomplete: 110,
    assigned: 10,
  },
  {
    name: "Financial and Accounting Records",
    total: 640,
    completed: 400,
    incomplete: 200,
    assigned: 40,
  },
  {
    name: "Tax Matters",
    total: 500,
    completed: 300,
    incomplete: 150,
    assigned: 50,
  },
  {
    name: "Loans and Obligations",
    total: 400,
    completed: 250,
    incomplete: 100,
    assigned: 50,
  },
  {
    name: "Property and Equipment",
    total: 300,
    completed: 180,
    incomplete: 70,
    assigned: 50,
  },
  {
    name: "Intellectual Property",
    total: 450,
    completed: 250,
    incomplete: 150,
    assigned: 50,
  },
  {
    name: "Material Contracts",
    total: 550,
    completed: 350,
    incomplete: 150,
    assigned: 50,
  },
  {
    name: "Operational Matters",
    total: 600,
    completed: 400,
    incomplete: 150,
    assigned: 50,
  },
  {
    name: "Litigation",
    total: 700,
    completed: 450,
    incomplete: 200,
    assigned: 50,
  },
  {
    name: "Regulatory Matters",
    total: 650,
    completed: 380,
    incomplete: 220,
    assigned: 50,
  },
  {
    name: "Environmental Matters",
    total: 350,
    completed: 200,
    incomplete: 100,
    assigned: 50,
  },
  {
    name: "Employment and Compensation Matters",
    total: 800,
    completed: 500,
    incomplete: 250,
    assigned: 50,
  },
  {
    name: "Data Privacy and Security",
    total: 750,
    completed: 450,
    incomplete: 250,
    assigned: 50,
  },
]
